### ISSUE TITLE
iedit-switch-to-mc-mode errors with Invalid function: mc/save-excursion

### ISSUE THREAD

**Issue by glucas** [victorhge/iedit#72]
I'm trying out the M-M (switch to multiple cursors) binding and it always fails for me with:

    iedit-switch-to-mc-mode: Invalid function: mc/save-excursion

I'm not sure what's wrong, `mc/save-excursion' is defined:

    mc/save-excursion is a Lisp macro in ‘multiple-cursors-core.el’.

**Comment by victorhge** [comment]
Strange thing.  Would you try to compile your 'multiple-corsors-core.el' to see if `mc/save-excursion' is valid?

**Comment by victorhge** [comment]
I just fixed a bug in this.  Would you try again?

**Comment by glucas** [comment]
I'm still seeing issues here with the latest changes. When I call `iedit-switch-to-mc-mode` I still get the error:

    iedit-switch-to-mc-mode: Invalid function: mc/save-excursion

but I do end up with multiple cursors. I think the error has some side-effects because the mc overlays don't clean up properly when I quit out of mc mode. 
I confirmed that `mc/cmds-to-run-once` does include `iedit-switch-to-mc-mode`. I'll experiment I bit more and let you know if I find anything. Thanks for tackling this!

**Comment by glucas** [comment]
If I open iedit-lib.el and manually evaluate the `(when (require...` form, things start to work properly. Not sure exactly what the means, though...

**Comment by victorhge** [comment]
I think I have got the root cause.  mc/save-excursion is a macro, which is unknown when iedit-lib is compiled.  So it is treated as function.  And there should be a warning message about this. 

It should have been fixed in the [last commit](https://github.com/victorhge/iedit/commit/02bad3e3b9e9d0414980b39751c6a80fd81a7192).

**Comment by glucas** [comment]
Yes, it's working now. Thanks!
